// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_tracker_app/test/features/Bookmarks/domain/usecases/remove_bookmark_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:crypto_tracker_app/core/error/failure.dart' as _i5;
import 'package:crypto_tracker_app/features/Bookmarks/domain/entities/coin.dart'
    as _i6;
import 'package:crypto_tracker_app/features/Bookmarks/domain/repositories/bookmark_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookmarkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkRepository extends _i1.Mock
    implements _i3.BookmarkRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> addBookmark(_i6.Coin? coin) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [coin]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#addBookmark, [coin]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>(
                    this,
                    Invocation.method(#addBookmark, [coin]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Coin>>> getAllBookmarked() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBookmarked, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Coin>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Coin>>(
                    this,
                    Invocation.method(#getAllBookmarked, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Coin>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Coin>>(
                    this,
                    Invocation.method(#getAllBookmarked, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Coin>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isBookmarked(_i6.Coin? coin) =>
      (super.noSuchMethod(
            Invocation.method(#isBookmarked, [coin]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isBookmarked, [coin]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>(
                    this,
                    Invocation.method(#isBookmarked, [coin]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> removeBookmark(
    _i6.Coin? coin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeBookmark, [coin]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#removeBookmark, [coin]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>(
                    this,
                    Invocation.method(#removeBookmark, [coin]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
